### ISSUE TITLE
Possibly missing a couple `ask [ ]` in `cwd-progression` procedure

### ISSUE THREAD

**Issue by kenkellner** [anyadoc/MOOvCWD_InfectionModel_BETA#1]
See lines below - fawns are queried in both cases but never asked to actually do anything:

https://github.com/anyadoc/MOOvCWD_InfectionModel_BETA/blob/4344c9ac78224f7579ce46ad76ac29ef32162223/MOOvCWD_v2.1.nlogo#L1081

https://github.com/anyadoc/MOOvCWD_InfectionModel_BETA/blob/4344c9ac78224f7579ce46ad76ac29ef32162223/MOOvCWD_v2.1.nlogo#L1230

I tested a change on my branch temporarily and found it greatly increased the rate of cwd spread, but I didn't keep the change because I didn't want to make any functional changes to the model just yet.

**Comment by anyadoc** [comment]
In both cases, they get infected (change cwd  to 1), right? Lines 1083 and 1232.

**Comment by kenkellner** [comment]
I think that infection check is being applied against the mother, though (who by definition already has to be cwd-positive)

Here's my annotated version of what the model currently does:
```
; Currently in context of mature female deer ("mother")
let my-fawns deers with [ momid = tmomid and cwd = 0 ]  ;select my fawns             
        if any? my-fawns in-radius 1.5 [ ; If I have fawns nearby, do the following
          if (aim = 3)[  ; if *mother* is age=3 (impossible) do the following:                                                      
            if (random-float 1 < (0.77 + random-float 0.24))[
              set cwd 1 ; mother is already cwd positive anyway, or she wouldn't be running this procedure
              ]
]
```
And what I think it should do:
```
; Currently in context of mature female deer ("mother")
let my-fawns deers with [ momid = tmomid and cwd = 0 ]  ;select my fawns             
        if any? my-fawns in-radius 1.5 [ ; If I have fawns nearby, do the following
          ask my-fawns in-radius 1.5 [ ; ask each fawn to do the following
              if (aim = 3)[  ; if *fawn* is age=3 do the following:                                                      
                  if (random-float 1 < (0.77 + random-float 0.24))[
                     set cwd 1 
              ]
        ]
]
```
Or a bit more efficiently:

```
; Currently in context of mature female deer ("mother")
  ask deers in-radius 1.5 with [ momid=tmomid and cwd=0] [ ; ask each fawn (if any exist) to do the following
          if (aim = 3)[  ; if *fawn* is age=3 do the following:                                                      
               if (random-float 1 < (0.77 + random-float 0.24))[
                     set cwd 1 
              ]
]
```

**Comment by kenkellner** [comment]
I ran some more tests, and the change I proposed doesn't actually have that much of an effect on cwd spread, my previous simulation run must have been an outlier.

**Comment by anyadoc** [comment]
That's a good catch, Ken. I have added 'ask my-fawns..' in the code. Thanks!
